spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Qlxemphim;encrypt=false
    username: sa
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true