spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Qlxemphim;encrypt=false
    username: sa
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  time-zone: Asia/Ho_Chi_Minh
  redis:
    host: localhost
    port: 6379
jwt:
  secretKey: "fvM5429XdKnajoAwXqMnhWNgVXFoAaGqS8gcs1lorUlt3n2EAwhKv5Yf+3ektFC7"